### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by qrkourier** [gilesknap/gphotos-sync#118]
While building the albums symlinks unable to continue with OS Error filename too long. I was unsuccessful locating any images in Photos by searching for various strings in the very long filename shown.

```❯ pipenv run gphotos-sync --retry-download --log-level error ~/Downloads/from_gphotos/
08-29 23:57:40 WARNING: skipped 1 files listed in /home/kbingham/Downloads/from_gphotos/gphotos.bad_ids.yaml                                                                   
08-29 23:57:48
Process failed.
Traceback (most recent call last):
  File "/home/kbingham/.local/share/virtualenvs/kbingham-ELItVadJ/lib/python3.7/site-packages/gphotos/Main.py", line 345, in main                                              
    self.start(args)
  File "/home/kbingham/.local/share/virtualenvs/kbingham-ELItVadJ/lib/python3.7/site-packages/gphotos/Main.py", line 317, in start                                             
    self.do_sync(args)
  File "/home/kbingham/.local/share/virtualenvs/kbingham-ELItVadJ/lib/python3.7/site-packages/gphotos/Main.py", line 303, in do_sync                                           
    self.google_albums_sync.create_album_content_links()
  File "/home/kbingham/.local/share/virtualenvs/kbingham-ELItVadJ/lib/python3.7/site-packages/gphotos/GoogleAlbumsSync.py", line 240, in create_album_content_links            
    link_file.symlink_to(relative_filename)
  File "/home/kbingham/.pyenv/versions/3.7.4/lib/python3.7/pathlib.py", line 1337, in symlink_to                                                                               
    self._accessor.symlink(target, self, target_is_directory)
  File "/home/kbingham/.pyenv/versions/3.7.4/lib/python3.7/pathlib.py", line 431, in symlink                                                                                   
    return os.symlink(a, b)
OSError: [Errno 36] File name too long: '../../../photos/2013/11/Kenneth_Bingham-pa_href_httpwww.pinterest.compin219409813067192167img_src_httpmedia-cache-ec0.pinimg.com192xda2056da205673c89241056750aa20dc68c7cb.jpg_style_border_noneappAesthetically_happy_at_14_Carrot_Cafep-Aesthetically_happy_at_14_Carrot_Cafe.jpg' -> '/home/kbingham/Downloads/from_gphotos/albums/2013/1106 Pinterest/0017_Kenneth_Bingham-pa_href_httpwww.pinterest.compin219409813067192167img_src_httpmedia-cache-ec0.pinimg.com192xda2056da205673c89241056750aa20dc68c7cb.jpg_style_border_noneappAesthetically_happy_at_14_Carrot_Cafep-Aesthetically_happy_at_14_Carrot_Cafe.jpg'                                                           
```

**Comment by gilesknap** [comment]
That is indeed a very long file name!

It should be relatively easy to add a check that will truncate filenames that won't fit on the file system.

I'll take a look.

**Comment by gilesknap** [comment]
I'm closing this and rolling up this requirement into #110
