### ISSUE TITLE
PY failures?

### ISSUE THREAD

**Issue by wills721** [gilesknap/gphotos-sync#133]
Having some new errors I have not seen before?

/home/will/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/b                                                                                                             in:/usr/games:/usr/local/games:/snap/bin:/usr/local/sbin:/usr/local/bin:/sbin:/b                                                                                                             in:/usr/sbin:/usr/bin
/home/will
Flush at startup
09-28 16:56:26 Indexing Google Photos Files ...
09-28 17:12:49 Indexing Shared (titled) Albums ...
09-28 17:22:03 Indexed 242 Shared (titled) Albums
09-28 17:22:03 Indexing Albums ...
09-28 17:26:09 Retrying (Retry(total=4, connect=None, read=None, redirect=None,                                                                                                              status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(                                                                                                             host='photoslibrary.googleapis.com', port=443): Read timed out. (read timeout=10                                                                                                             )",)': /v1/mediaItems:search
09-28 17:29:44 Retrying (Retry(total=4, connect=None, read=None, redirect=None,                                                                                                              status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(                                                                                                             host='photoslibrary.googleapis.com', port=443): Read timed out. (read timeout=10                                                                                                             )",)': /v1/mediaItems:search
09-28 17:30:19 Indexed 76 Albums
09-28 17:30:19 Downloading Photos ...
09-28 17:32:29 FAILURE 1 downloading photos/2017/12/IMG_1675.JPG
09-28 17:32:29 FAILURE 2 downloading photos/2017/12/IMG_1675.JPG
09-28 17:32:29
Process failed.
Traceback (most recent call last):
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-pac                                                                                                             kages/gphotos/Main.py", line 373, in main
    self.start(args)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-pac                                                                                                             kages/gphotos/Main.py", line 345, in start
    self.do_sync(args)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-pac                                                                                                             kages/gphotos/Main.py", line 329, in do_sync
    self.google_photos_down.download_photo_media()
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-pac                                                                                                             kages/gphotos/GooglePhotosDownload.py", line 133, in download_photo_media
    self.do_download_complete(futures_left)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-pac                                                                                                             kages/gphotos/GooglePhotosDownload.py", line 265, in do_download_complete
    raise e
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-pac                                                                                                             kages/gphotos/GooglePhotosDownload.py", line 129, in download_photo_media
    self.download_batch(batch)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-pac                                                                                                             kages/gphotos/GooglePhotosDownload.py", line 167, in download_batch
    self.download_file(media_item, media_item_json)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-pac                                                                                                             kages/gphotos/GooglePhotosDownload.py", line 198, in download_file
    self.do_download_complete(done_list)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-pac                                                                                                             kages/gphotos/GooglePhotosDownload.py", line 265, in do_download_complete
    raise e
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-pac                                                                                                             kages/gphotos/GooglePhotosDownload.py", line 233, in do_download_file
    Utils.safe_timestamp(media_item.create_date)))
FileNotFoundError: [Errno 2] No such file or directory
09-28 17:32:29 Done.
Re-scanning at startup
09-28 17:32:33 Indexing Google Photos Files ...
09-28 17:45:23 Indexing Shared (titled) Albums ...
09-28 17:54:40 Indexed 242 Shared (titled) Albums
09-28 17:54:40 Indexing Albums ...

**Comment by gilesknap** [comment]
Thanks,

It looks like you had some connection issues and a timeout on downloading
new images. It also looks like I may have introduced a bug with attempting
to set the timestamp after download failed.

Investigating.

**Comment by wills721** [comment]
Not sure if it helps but here are more: 

  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/Main.py", line 373, in main
    self.start(args)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/Main.py", line 345, in start
    self.do_sync(args)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/Main.py", line 326, in do_sync
    self.google_albums_sync.index_album_media()
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 121, in index_album_media
    False, True)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 163, in index_albums_type
    album.id, add_media_items)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 110, in fetch_album_contents
    response = self._api.mediaItems.search.execute(body)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/restclient.py", line 86, in execute
    result.raise_for_status()
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://photoslibrary.googleapis.com/v1/mediaItems:search
09-30 06:24:23 Done.
Scanning at startup
Mon Sep 30 06:24:23 EDT 2019 Run 1
09-30 06:24:27 Indexing Google Photos Files ...
09-30 06:24:28 Indexing Shared (titled) Albums ...
09-30 06:24:28
Process failed.
Traceback (most recent call last):
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/Main.py", line 373, in main
    self.start(args)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/Main.py", line 345, in start
    self.do_sync(args)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/Main.py", line 326, in do_sync
    self.google_albums_sync.index_album_media()
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 121, in index_album_media
    False, True)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 138, in index_albums_type
    response = api_function(pageSize=50)
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/gphotos/restclient.py", line 86, in execute
    result.raise_for_status()
  File "/home/will/.local/share/virtualenvs/will-PWwV11kO/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://photoslibrary.googleapis.com/v1/sharedAlbums?pageSize=50
09-30 06:24:28 Done.

**Comment by gilesknap** [comment]
When you get 'Too Many Requests for url:' That means you have exceeded quota on free access to Google APIs. You just need to wait for a bit (at most a day but probably less) and your quota will reset.

In this instance, gphotos-sync is erroring correctly.

**Comment by wills721** [comment]
So maybe what I do is overkill but my linux server gets booted every day and polls. This is my shell script at boot time (its possible today it booted twice I was doing something unrelated on the same server):

#!/bin/bash
export HOME=/home/will
export PATH="/home/will/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:$PATH"
echo $PATH
echo $HOME
echo "Flush at startup"
pipenv run gphotos-sync --flush-index /mnt/Photos
echo "Re-scanning at startup"
pipenv run gphotos-sync --rescan /mnt/Photos
counter=1
echo "Scanning at startup"
while :
do
    echo "$(date) Run $counter"
    cd /home/will/gphotos-sync
    pipenv run gphotos-sync /mnt/Photos
    ((counter++))
    sleep 600
done
echo 'Exiting'

**Comment by gilesknap** [comment]
Since you are doing --flush-index it will be doing a full re-index each time, that is quite a few API calls. If you do that every 10 minutes you will hit quota. You would be OK to do a --flush-index once a day probably (I can with 130,000 items in my library)

**Comment by wills721** [comment]
The flush and the re-index are each once a day as long as my linux instance reboots only once a day (which it normally does).  The loop in the script is just the normal plain run.

**Comment by gilesknap** [comment]
I just got this error while playing with vs code. Removing pywin32 worked. I need to make this OS-dependent.

**Comment by wills721** [comment]
Do I need a new version to download or is the error just benign?

**Comment by wills721** [comment]
I'm noticing some strange things that may be related.  I seem to be having cases where gphotos is placing files in the wrong date locations.

**Comment by gilesknap** [comment]
I think all the errors you have are benign. You may find you need to delete the BadIds file in order to download any files that got listed there because of temporary errors.

The issue with setting the timestamp needs a fix from me, but its just to tidy things up. It wont cause any change in behaviour (other than a shorter error message).

**Comment by gilesknap** [comment]
Looking at the error:
```
Utils.safe_timestamp(media_item.create_date)))
FileNotFoundError: [Errno 2] No such file or directory
```
I now see, based on our offline discussion, that this is due to your NAS seeing a filename clash.

As discussed we need a flag to say that the filesystem is case insensitive. I would love to be able to do this automatically when doing other filesystem checks. This is because it will bite people in a hard to diagnose fashion if they do not know to set this flag for their setup.

The obvious approach of creating two files to see if they clash won't work for NAS as you point out since the NAS will change the file name immediately when it sees a clash.

However, I could do this in the target folder:-

- create '.filesystem.check' directory 
- within this directory:-
- create 'temp.test'
- create 'TEMP.test' --- if this fails then we have a normal case insensitive file system
- read out the contents of the directory --- if not as expected we have a case insensitive NAS

Or perhaps a simpler option:-
- create 'TeMp.TeSt
- read the directory and if the file is not mixed case then we have case insensitive filesystem

**Comment by wills721** [comment]
I think the first one would work.  The second one may come back correct (my case is I run on Ubuntu but mount the share also on SMB)

**Comment by mprenditore** [comment]
> I think the first one would work. The second one may come back correct (my case is I run on Ubuntu but mount the share also on SMB)

I've implemented the second method since it seems reliable.
As soon as it's merged you can try it, if it doesn't fix your problem I'll try implement the first option.

**Comment by wills721** [comment]
The problem I see with the second method is it will not generate the error for my scenario.  I use Ubuntu but my NAS also exposes my volume elsewhere as an SMB share.  Only when a second write occurs will this result in my NAS generating a new file with a new name ('TEMP-CaseConflictmmddyy.test'.

**Comment by mprenditore** [comment]
> The problem I see with the second method is it will not generate the error for my scenario. I use Ubuntu but my NAS also exposes my volume elsewhere as an SMB share. Only when a second write occurs will this result in my NAS generating a new file with a new name ('TEMP-CaseConflictmmddyy.test'.

I see, but if I create a file *Temp.File* from what I did understand is that the NAS automatically convert it to lowercase, is that right? So if I should have an error if I try to read *Temp.File* but not *temp.file*. Or I mis-interpreted that?

**Comment by wills721** [comment]
No.  Under Ubuntu it will appear as normal due to that file system (e.g. its FAT).  However,  over on the SMB side it will appear all upper case and when you try to create another it will generate the NAS logic to change up the file name

**Comment by gilesknap** [comment]
It looks like the first approach would work then. 

Also, the nice thing about the first approach is that you can do a recursive delete on the .filesystem.check folder to get rid of the test files, thus it does not matter what filename the NAS generates.

I'm just working on the merge right now.

**Comment by mprenditore** [comment]
> It looks like the first approach would work then.
> 
> Also, the nice thing about the first approach is that you can do a recursive delete on the .filesystem.check folder to get rid of the test files, thus it does not matter what filename the NAS generates.
> 
> I'm just working on the merge right now.

so, you're going to implement it? perfect :)

**Comment by gilesknap** [comment]
Closing as we are covering the issue of NAS duplicates in #110

**Comment by gilesknap** [comment]
@wills721 I believe your NAS case insensitive clashes should now work OK. I have implemented our suggested fix to determining case-insensitivity of the filesystem.

It is checked into master if you would like to give it a try

**Comment by wills721** [comment]
Excellent!  The last time I upgraded I performed this 'pipenv install gphotos-sync=2.10.1'

This still correct way and what is the new version? 

Thanks for following up!

**Comment by gilesknap** [comment]
Hi, I have not released the changes so you would need to install from the master branch of github.

To do so, cd to your gphotos-sync directory and execute
```
pipenv install git+https://github.com/gilesknap/gphotos-sync.git#egg=gphotos-sync
```
