### ISSUE TITLE
Unhandled KeyError: 'APP1' in get_image_date

### ISSUE THREAD

**Issue by KrisKennaway** [gilesknap/gphotos-sync#144]
I'm getting errors of this form when trying to use --compare-folder (on 2.10.1):

10-23 21:04:20 file /tank/photos/drive/Google Photos/2015/2015-11-07.jpg could not be made into a media obj
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalFilesScan.py", line 73, in index_local_item
    lf = LocalFilesMedia(path)
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalFilesMedia.py", line 65, in __init__
    self.get_image_date()
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalFilesMedia.py", line 96, in get_image_date
    p_date = Utils.string_to_date(self.__exif.datetime_original)
  File "/usr/local/lib/python3.7/site-packages/exif/_image.py", line 78, in __getattr__
    return getattr(self._segments['APP1'], item)
KeyError: 'APP1'

The file in question does seem to be a valid JPG.  I can open it in OS X Preview, and:

$ file "/tank/photos/drive/Google Photos/2015/2015-11-07.jpg"
/tank/photos/drive/Google Photos/2015/2015-11-07.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 2448x3264, frames 3

**Comment by KrisKennaway** [comment]
Reading https://dev.exiv2.org/projects/exiv2/wiki/The_Metadata_in_JPEG_files I think this is because it's (for some reason) not an EXIF format JPEG.

**Comment by gilesknap** [comment]
Hi Kris,

Nice to know someone is using the comparison feature. (it probably needs a little work to make it more friendly).

Is this error aborting the comparison or is it just showing up in the debug log?

If it is the latter then that just means the matching capability will be limited since we can't see any metadata. If it is the former then this is a bug but should be easy to fix.

**Comment by KrisKennaway** [comment]
It aborts the program, so perhaps it's just a matter of catching the
exception.  Though for files with a JFIF header potentially there is
metadata that could be extracted from there instead.  That'd be more work,
though presumably there are libraries that can read both.

Full stacktrace:

Process failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 373,
in main
    self.start(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 345,
in start
    self.do_sync(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 337,
in do_sync
    self.local_files_scan.scan_local_files()
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalFilesScan.py",
line 48, in scan_local_files
    self.scan_folder(self._scan_folder, self.index_local_item)
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalFilesScan.py",
line 59, in scan_folder
    self.scan_folder(pth, index)
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalFilesScan.py",
line 59, in scan_folder
    self.scan_folder(pth, index)
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalFilesScan.py",
line 62, in scan_folder
    self.count += index(pth)
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalFilesScan.py",
line 73, in index_local_item
    lf = LocalFilesMedia(path)
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalFilesMedia.py",
line 65, in __init__
    self.get_image_date()
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalFilesMedia.py",
line 96, in get_image_date
    p_date = Utils.string_to_date(self.__exif.datetime_original)
  File "/usr/local/lib/python3.7/site-packages/exif/_image.py", line 78, in
__getattr__
    return getattr(self._segments['APP1'], item)
KeyError: 'APP1'
10-23 21:04:21 Done.

**Comment by gilesknap** [comment]
Thanks I'll take s look at supporting jfif.

**Comment by gilesknap** [comment]
I just realized that I already fixed this but have not done a release since. Releasing 2.10.2 ...
(this will just ignore the error and treat JFIF as having no metadata.

**Comment by gilesknap** [comment]
closing as fixed in 2.10.2
