### ISSUE TITLE
database locked

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#146]
Just got a new error - haven't changed anything I do to run this and on the same drive too.

`11-02 19:27:44 EXITING: database is locked`

A bit more context

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1241, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/photography/phone/go/mobile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1241, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/photography/phone/go'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1241, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/photography/phone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/bin/gphotos-sync", line 10, in <module>
    sys.exit(main())
  File "/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/gphotos/Main.py", line 359, in main
    GooglePhotosSyncMain().main()
  File "/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/gphotos/Main.py", line 326, in main
    root_folder.mkdir(parents=True, mode=0o700)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1245, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1245, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1245, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1241, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Volumes/photography'
(.venv) gomachan:gphotos-sync-master gomachan$ 
```

**Comment by gilesknap** [comment]
> PermissionError: [Errno 13] Permission denied: '/Volumes/photography'
I think the above is the relevant error - it looks like you do not have write permission on the folder in which you are trying to create the photos store.

I think it is a bug that it reports 'database is locked' Are you running on a Mac?

**Comment by gosugimoto** [comment]
Yes. Through the virtual thing on terminal.

**Comment by gilesknap** [comment]
Please can you check the file permissions on the folder /Volumes/photography.

**Comment by gosugimoto** [comment]
Ah yes, somehow the entire drive got locked!  Thank you!!
