### ISSUE TITLE
Upgrade of DB Schema fails on photos download

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/gphotos-sync#148]
When the DB is upgraded to a new version, this is OK for indexing. 

However, when we get to download phase the first attempt to access the database raises a database closed error.

I assume this is because the GooglePhotosIndex and GooglePhotosDownload objects have separate copies of the connection object.

**Comment by gilesknap** [comment]
The log looked like this:-

```
11-03 21:11:14 gphotos.GoogleAlbumsSync DEBUG    ----f1.jpg
11-03 21:11:14 gphotos.GoogleAlbumsSync DEBUG    Adding album media item photos/1998/10/f1.jpg f1.jpg 0
11-03 21:11:14 gphotos.GoogleAlbumsSync INFO     Indexing Album: Pembrokeshire holiday, photos: 0
11-03 21:11:15 gphotos.GoogleAlbumsSync INFO     Indexing Album: Wont Download, photos: 0
11-03 21:11:16 gphotos.GoogleAlbumsSync INFO     Indexing Album: Untitled, photos: 0
11-03 21:11:17 gphotos.GoogleAlbumsSync WARNING  Indexed 385 Albums
11-03 21:11:17 gphotos.GooglePhotosDownload WARNING  Downloading Photos ...
11-03 21:11:17 gphotos.LocalData ERROR    query: SELECT Id,RemoteId,Uid,Url,Path,FileName,OrigFileName,DuplicateNo,FileSize,MimeType,Description,ModifyDate,CreateDate,SyncDate,Downloaded,Location FROM SyncFiles WHERE RemoteId LIKE ? AND FileName LIKE ? and Path LIKE ? AND Downloaded IS 0;
params: ('%', '%', '%')
11-03 21:11:17 gphotos.GooglePhotosDownload WARNING  Downloaded 0 Items, Failed 0, Already Downloaded 0
11-03 21:11:17 gphotos.LocalData INFO     Saving Database ...
11-03 21:11:17 gphotos.LocalData INFO     Database Saved.
11-03 21:11:17 gphotos.Main ERROR    
Process failed.
Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/Main.py", line 410, in main
    self.start(args)
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/Main.py", line 363, in start
    self.do_sync(args)
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/Main.py", line 347, in do_sync
    self.google_photos_down.download_photo_media()
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 116, in download_photo_media
    skip_downloaded=not self.retry_download)):
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/LocalData.py", line 205, in get_rows_by_search
    self.cur2.execute(query, params)
sqlite3.ProgrammingError: Cannot operate on a closed database.
11-03 21:11:17 gphotos.Main WARNING  Done.
11-03 21:11:17 gphotos.Main INFO     Elapsed time = 0:28:33.532667

```

**Comment by gilesknap** [comment]
fixed in https://github.com/gilesknap/gphotos-sync/commit/a97a222c8f28bc1af0d0633e96184792eb351c00
