### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by tjbaker** [gilesknap/gphotos-sync#149]
I am getting the following exception:

version: 2.10.1, database schema version 5.6
`gphotos-sync therootfolder`

```
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gphotos-sync", line 11, in <module>
    load_entry_point('gphotos-sync==2.10.1', 'console_scripts', 'gphotos-sync')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gphotos/Main.py", line 387, in main
    GooglePhotosSyncMain().main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gphotos/Main.py", line 373, in main
    self.start(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gphotos/Main.py", line 345, in start
    self.do_sync(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gphotos/Main.py", line 329, in do_sync
    self.google_photos_down.download_photo_media()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 129, in download_photo_media
    self.download_batch(batch)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 163, in download_batch
    i, r_json, result
Message: 'Null response in mediaItems.batchGetfor item &d in\n\n %s \n\n which is \n%s'
Arguments: (11, {'mediaItemResults': [{'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}}, {'mediaItem': {'id': 'redacted', 'productUrl': 'https://photos.google.com/lr/photo/redacted', 'mimeType': 'image/jpeg', 'mediaMetadata': {'creationTime': '2019-11-06T13:45:44Z', 'width': '3840', 'height': '2160', 'photo': {'cameraMake': 'Google', 'cameraModel': 'Pixel 3', 'focalLength': 4.44, 'apertureFNumber': 1.8, 'isoEquivalent': 55}}, 'filename': 'IMG_20191106_084544.jpg'}}]}, {'status': {'code': 3, 'message': 'Invalid media item ID.'}})
```

**Comment by gilesknap** [comment]
Thanks for the detailed report.

The code that is failing is my workaround to an occasional Google API bug and it looks like it cant convert some of the parameters in the warning log to strings. I have made an attempt at fixing this in the master branch. Please can you try it out.

This also tells me I need to increase code coverage on the tests and include failure paths like this one.

**Comment by gilesknap** [comment]
Oh, and my 7-year-old son likes your Github avatar! :-)

**Comment by gilesknap** [comment]
Did you manage to try master to see if it fixed your issue?

**Comment by gilesknap** [comment]
I believe this is fixed. Closing. I have opened #158 to cover error code in the tests to avoid future incidents like this.
