### ISSUE TITLE
Crash, and it's creating local albums even though I don't have any albums

### ISSUE THREAD

**Issue by ctrager** [gilesknap/gphotos-sync#163]
/snap/bin/gphotos-sync --start-date 2018-09-01 --secret ~/gphotos-sync/client_secret.json  ~/gphotos-sync/pics
11-30 18:55:53 WARNING  Indexing Google Photos Files ... 
11-30 18:55:55 WARNING  Indexing Shared (titled) Albums ... 
--- Logging error ---
Traceback (most recent call last):
  File "/snap/gphotos-sync/44/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 66: ordinal not in range(128)
Call stack:
  File "/snap/gphotos-sync/44/bin/gphotos-sync", line 11, in <module>
    load_entry_point('gphotos-sync==2.10.3', 'console_scripts', 'gphotos-sync')()
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/Main.py", line 424, in main
    GooglePhotosSyncMain().main()
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/Main.py", line 410, in main
    self.start(args)
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/Main.py", line 363, in start
    self.do_sync(args)
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/Main.py", line 344, in do_sync
    self.google_albums_sync.index_album_media()
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 123, in index_album_media
    False, True)
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 159, in index_albums_type
    album.size)
Message: 'Skipping Album: %s, photos: %d'
Arguments: ('C\xf3rdoba, Madrid one night, Spain 7/13-17/2018', 303)
11-30 18:55:57 WARNING  Indexed 22 Shared (titled) Albums 
11-30 18:55:57 WARNING  Indexing Albums ... 
11-30 18:55:57 WARNING  Indexed 0 Albums 
11-30 18:55:57 WARNING  Downloading Photos ... 
11-30 18:55:57 WARNING  Downloaded 0 Items, Failed 0, Already Downloaded 173 
11-30 18:55:57 WARNING  Creating album folder links to media ... 
--- Logging error ---
Traceback (most recent call last):
  File "/snap/gphotos-sync/44/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 172: ordinal not in range(128)
Call stack:
  File "/snap/gphotos-sync/44/bin/gphotos-sync", line 11, in <module>
    load_entry_point('gphotos-sync==2.10.3', 'console_scripts', 'gphotos-sync')()
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/Main.py", line 424, in main
    GooglePhotosSyncMain().main()
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/Main.py", line 410, in main
    self.start(args)
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/Main.py", line 363, in start
    self.do_sync(args)
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/Main.py", line 349, in do_sync
    self.google_albums_sync.create_album_content_links()
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 247, in create_album_content_links
    link_file)
Message: 'adding album link %s -> %s'
Arguments: ('../../../../../photos/2018/07/IMG_20180713_165026.jpg', PosixPath('/home/corey/gphotos-sync/pics/albums/2018/0717 C\xf3rdoba, Madrid one night, Spain 7/13-17/2018/0000_IMG_20180713_165026.jpg'))
11-30 18:55:58 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/Main.py", line 410, in main
    self.start(args)
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/Main.py", line 363, in start
    self.do_sync(args)
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/Main.py", line 349, in do_sync
    self.google_albums_sync.create_album_content_links()
  File "/snap/gphotos-sync/44/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 249, in create_album_content_links
    if not link_folder.is_dir():
  File "/snap/gphotos-sync/44/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/snap/gphotos-sync/44/usr/lib/python3.6/pathlib.py", line 1158, in stat
    return self._accessor.stat(self)
  File "/snap/gphotos-sync/44/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 48: ordinal not in range(128)
11-30 18:55:58 WARNING  Done.

**Comment by gilesknap** [comment]
Hi. Sorry, this is a bit of a nasty fail, the exception handling needs improvement it seems.

According to the log you sent the code has found an album in your library called "Madrid, one night, Spain 7/14. It looks like the album name has an emoticon at the beginning. We are supposed to trap whether the file system can handle emoticons, but I have yet to fix that, see https://github.com/gilesknap/gphotos-sync/issues/110#issuecomment-539041420.

If you do not think you have any albums, it is possible this is coming from shared albums in which case the option --skip-shared-albums may work around your issue.

**Comment by gilesknap** [comment]
By the way, I did not create the snap and when I tried to test it the other day, I could not work out how to give it write permission to the host file system. Can you give me any tips? Thanks.

**Comment by ctrager** [comment]
(as you probably know...) Google Photos lets you share your entire library (as opposed to album-by-album) but with just one person. My wife shares her entire library with me. She has an album "Córdoba, Madrid one night, Spain 7/13-17/2018", so it's that accent in "Córdoba" that causes the problem.  I tried --skip-shared-albums, but sync still sees my wife's album and crashes. I tried --skip-albums and that bypassed the problem and sync didn't crash.

Regarding write permission, I didn't do anything. I using Linux Mint and I installed snapd itself using their own Software Manager app.

**Comment by gilesknap** [comment]
I believe the API will not distinguish between your wife's and your own
libraries in this case. So the syncing of her albums is expected.

Can you let me know what the filesystem is of your backup target? I have
accents in album names on Linux using ext4 with no issues. I assume you are
using a different filesystem and you need a fix to the issue I referenced
previously. This should be done soonish (probably over the winter holidays).

**Comment by ctrager** [comment]
```
corey@x220b:~$ df -Th
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  3.8G     0  3.8G   0% /dev
tmpfs          tmpfs     785M  1.4M  784M   1% /run
/dev/sda1      ext4      117G   78G   34G  71% /
tmpfs          tmpfs     3.9G  245M  3.6G   7% /dev/shm
tmpfs          tmpfs     5.0M  4.0K  5.0M   1% /run/lock
tmpfs          tmpfs     3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs          tmpfs     785M   60K  785M   1% /run/user/1000
/dev/loop0     squashfs   23M   23M     0 100% /snap/snapd/5306
/dev/loop1     squashfs   55M   55M     0 100% /snap/core18/1265
/dev/loop2     squashfs   13M   13M     0 100% /snap/gphotos-sync/44

```

**Comment by ctrager** [comment]
Me personally, I don't need a fix.

**Comment by gilesknap** [comment]
You have ext4 too. Maybe I have a regression, thanks for the info.

**Comment by gilesknap** [comment]
@ctrager. The latest version in master should fix this issue and replace Unicode characters if your filesystem does not accept them.
