### ISSUE TITLE
TokenExpiredError

### ISSUE THREAD

**Issue by flurl** [gilesknap/gphotos-sync#180]
Hi!

I'm using gphotos-sync and I keep getting TokenExpiredError after a while (about half a day).

For example the output of `gphotos-sync --do-delete --flush-index --album Bilderrahmen slideshow/gphotos/`:

```
01-05 08:25:47 ERROR
Process failed.
Traceback (most recent call last):
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 478, in request                                                                       
    url, http_method=method, body=data, headers=headers
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token                                                                 
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/gphotos/Main.py", line 397, in main
    self.setup(args, db_path)
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/gphotos/Main.py", line 242, in setup                                                                                             
    photos_api_url, self.auth.session
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/gphotos/restclient.py", line 37, in __init__                                                                                     
    service_document = self.auth_session.get(api_url).json()
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/requests/sessions.py", line 546, in get                                                                                          
    return self.request('GET', url, **kwargs)
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 497, in request                                                                       
    self.auto_refresh_url, auth=auth, **kwargs
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 446, in refresh_token                                                                 
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response                                               
    self.token = parse_token_response(body, scope=scope)
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response                                                        
    validate_token_parameters(params)
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters                                                   
    raise_from_error(params.get('error'), params)
  File "/home/pi/piFrame/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error                                                                
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError: (unauthorized_client) Unauthorized
01-05 08:25:47 WARNING  Done.
```
Two things worth noting:
- I run gphotos sync from within Django
- I use a cron job to run it every 15 mins

After getting this error I have to run gphotos-sync  withe `--new-token` and it starts working again.

I have to admit, I don't know very much about how oauth works. But my best guess is, that I'm running against some limit set by google, because on my development device this didn't happen yet and there I'm not running gphotos-sync periodically.

Do I have to renew the token after a specific amount of request? Am I doing something wrong?

**Comment by gilesknap** [comment]
I don't redo my Auth token often so don't recall the process in detail

I think there is an option during token creation to allow a refresh token.
You need the refresh token for gphotos to work. Please can you recreate
your Auth token and keep an eye out for the refresh option.

See the Linux uprising link at the top of the Readme for a good tutorial on
creating tokens.

**Comment by alexbaucom17** [comment]
I had the same issue. I generated a new token on google's api site, but was unable to find an option for allowing a refresh. But using the `--new-token` option specified above did work for me.

**Comment by gilesknap** [comment]
Thanks for confirming you also have the issue @alexbaucom17 
I have reviewed the token creation process and can't see anywhere to specify if refresh tokens are to be supplied.
You should definitely not be required to provide credentials every time you connect. I have not supplied mine for 2 years and just relied on automatic refresh.

Please can you both answer a few questions to see if we can find a common cause?:

- do you have a G suite Google account or a normal end-user account?
- please, can you supply the command line parameters you are using for gphotos-sync?
- how long ago did you first create your client secret token?

**Comment by alexbaucom17** [comment]
@gilesknap Thanks for investigating.

- I have a regular Google Account
- I was not using any special command line parameters, just `pipenv run gphotos-sync TARGET_DIRECTORY` (previously from within a script triggered by a cron job, and last night I switched to using the docker container method)
- I created my first client secret on July 1, 2019. I believe it stopped working sometime in mid-November and I just didn't realize it until last night. The last pictures I had backed up were from November and my Google API console showed no activity on my client secret in the last 30 days.

**Comment by gilesknap** [comment]
@alexbaucom17 thanks for the info.

When you generated the new token, did you still find that that expired too?

**Comment by alexbaucom17** [comment]
Yes it did until I re-ran `gphotos-sync` with the `--new-token` flag and went through the authorization process again. After that it worked fine.

**Comment by flurl** [comment]
@gilesknap 
- regular Google account
- `gphotos-sync --do-delete --flush-index --album Bilderrahmen slideshow/gphotos/` is the command I use
- I created the client secret on 2020-01-02

I use gphotos-sync in a digital picture frame. First I had a cron job running every 15 mins and the TokenExpiredError occured after about half a day. After renewing it stopped working again after about half a day. Then I changed the cron interval to 1h and now it's still working after about 48h.

I set up a test environment and will try some different intervals.

**Comment by gilesknap** [comment]
@flurl did you try creating another client yet?
If not please can you go to the Google API console and create a second client secret and install that one. You will need to use --new-token the first time after you have done so.

It sounds like the above steps worked for  @alexbaucom17

**Comment by flurl** [comment]
No, I didn't try it yet, but for whatever reason I can't reproduce the problem anymore. Running for 5 days now.
I'll keep an eye on it, but perhaps it was just a small hiccup on google's side.

**Comment by alexbaucom17** [comment]
I also seem to be running smoothly again after setting up a new secret and re-running the token authorization. I haven't seen the issue re-occur after that.

**Comment by gilesknap** [comment]
Thanks.

I can't explanation this but at least we have a workaround. 

Closing for now.
