### ISSUE TITLE
filesystem permissions under snapd

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/gphotos-sync#191]
Hi @popey,

I tried to run the gphotos-sync snap again and it installed and ran easily. However, I have two issues relating to filesystems that means it does not work for me.

(this is all on a fully updated Ubuntu 19.10)

I usually back up my photos to a secondary disk that is mounted as follows:
```/dev/sdb1      fuseblk   1.9T  1.6T  305G  84% /media/Data```

My snap does not have permission to write here, even if I set permissions to all writeable:

```
(master) [giles@gklinux gphotos-sync]$ ls -al /media/Data/tmp/gphotos-test
total 116
drwxrwxrwx 1 giles giles   4096 Feb  1 11:09 .
drwxr-xr-x 1 giles giles      0 Feb  1 10:56 ..
-rw-rw-rw- 1 giles giles      0 Feb  1 11:09 gphotos.lock
-rw-rw-rw- 1 giles giles   1585 Feb  1 11:09 gphotos.log
-rw-rw-rw- 1 giles giles 110592 Feb  1 11:02 gphotos.sqlite
-rw-rw-rw- 1 giles giles      0 Feb  1 11:09 gphotos.trace
(master) [giles@gklinux gphotos-sync]$ snap run gphotos-sync /media/Data/tmp/gphotos-test --secret /home/giles/github//gphotos-sync/test/test_credentials/client_secret.json
Traceback (most recent call last):
  File "/snap/gphotos-sync/92/bin/gphotos-sync", line 11, in <module>
    load_entry_point('gphotos-sync==2.10.4', 'console_scripts', 'gphotos-sync')()
  File "/snap/gphotos-sync/92/lib/python3.6/site-packages/gphotos/Main.py", line 412, in main
    GooglePhotosSyncMain().main()
  File "/snap/gphotos-sync/92/lib/python3.6/site-packages/gphotos/Main.py", line 378, in main
    self.logging(args, root_folder)
  File "/snap/gphotos-sync/92/lib/python3.6/site-packages/gphotos/Main.py", line 309, in logging
    filemode='w')
  File "/snap/gphotos-sync/92/usr/lib/python3.6/logging/__init__.py", line 1808, in basicConfig
    h = FileHandler(filename, mode)
  File "/snap/gphotos-sync/92/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/snap/gphotos-sync/92/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/media/Data/tmp/gphotos-test/gphotos.log'
```

However, if I write to /tmp it does have permission and works except for another caveat that I'll discuss in a second issue.

FYI my mounts look like this:
```
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  9.8G     0  9.8G   0% /dev
tmpfs          tmpfs     2.0G  4.3M  2.0G   1% /run
/dev/sdc2      ext4      457G  325G  110G  75% /
tmpfs          tmpfs     9.8G  1.2G  8.7G  12% /dev/shm
tmpfs          tmpfs     5.0M  4.0K  5.0M   1% /run/lock
tmpfs          tmpfs     9.8G     0  9.8G   0% /sys/fs/cgroup
/dev/loop3     squashfs  157M  157M     0 100% /snap/gnome-3-28-1804/110
/dev/loop4     squashfs   90M   90M     0 100% /snap/core/8213
/dev/loop1     squashfs  4.3M  4.3M     0 100% /snap/gnome-calculator/536
/dev/loop5     squashfs   15M   15M     0 100% /snap/remmina/3754
/dev/loop6     squashfs   45M   45M     0 100% /snap/gtk-common-themes/1353
/dev/loop8     squashfs   74M   74M     0 100% /snap/audacity/532
/dev/loop9     squashfs   90M   90M     0 100% /snap/core/8268
/dev/loop10    squashfs   15M   15M     0 100% /snap/gnome-characters/375
/dev/loop11    squashfs   15M   15M     0 100% /snap/remmina/3810
/dev/loop12    squashfs  4.3M  4.3M     0 100% /snap/gnome-calculator/544
/dev/loop15    squashfs  256K  256K     0 100% /snap/gtk2-common-themes/5
/dev/loop16    squashfs  1.0M  1.0M     0 100% /snap/gnome-logs/81
/dev/sdc1      vfat      511M  7.8M  504M   2% /boot/efi
/dev/sdb1      fuseblk   1.9T  1.6T  305G  84% /media/Data
tmpfs          tmpfs     2.0G   20K  2.0G   1% /run/user/124
/dev/sdd1      ext4      1.8T  779G  961G  45% /media/giles/GKBACKUP6
tmpfs          tmpfs     2.0G   52K  2.0G   1% /run/user/1001
tmpfs          tmpfs     2.0G   64K  2.0G   1% /run/user/1002
/dev/loop17    udf       5.1G  5.1G     0 100% /media/woeusb_source_1578945097_12994
/dev/loop18    squashfs   45M   45M     0 100% /snap/gtk-common-themes/1440
/dev/loop19    squashfs   55M   55M     0 100% /snap/core18/1650
tmpfs          tmpfs     2.0G   92K  2.0G   1% /run/user/1000
/dev/loop7     squashfs   74M   74M     0 100% /snap/audacity/573
/dev/loop2     squashfs   15M   15M     0 100% /snap/gnome-characters/399
/dev/loop20    squashfs  161M  161M     0 100% /snap/gnome-3-28-1804/116
/dev/loop0     squashfs   55M   55M     0 100% /snap/core18/1668
/dev/loop13    squashfs   14M   14M     0 100% /snap/gphotos-sync/92
```

**Comment by popey** [comment]
`snap connect gphotos-sync:removable-media` will fix that. I may request that's autoconnected too.

**Comment by gilesknap** [comment]
`snap connect gphotos-sync:removable-media` does indeed fix this issue, Thanks.

For some reason, I do not need to do `snap connect gphotos-sync:mount-observe`.
