### ISSUE TITLE
some sort of error

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#204]
I keep getting this now, nothing has changed.  I have 2 accounts syncing and the other one is fine...Any ideas?

03-05 12:15:57 WARNING  Case insensitive file system found 
03-05 12:15:57 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 395, in request
    http_method=method, body=data, headers=headers)
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/gphotos/Main.py", line 397, in main
    self.setup(args, db_path)
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/gphotos/Main.py", line 242, in setup
    photos_api_url, self.auth.session
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/gphotos/restclient.py", line 37, in __init__
    service_document = self.auth_session.get(api_url).json()
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 408, in request
    self.auto_refresh_url, auth=auth, **kwargs
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 374, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 415, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/Users/me/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Bad Request
03-05 12:15:57 WARNING  Done. 
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by gilesknap** [comment]
It looks like your refresh token has stopped working. I'm not sure why this happens.

You should be able to fix it by using the argument `--new-token`. This will ask you for your credentials again and will create a new token and refresh token.

**Comment by gosugimoto** [comment]
Brilliant, that seemed to do the trick.  Thanks again always!!!!
I love this script, it's solved everything!
--
iamgo.net

**Comment by gilesknap** [comment]
glad to help.
