### ISSUE TITLE
sqlite3.OperationalError: no such table: Globals

### ISSUE THREAD

**Issue by jorythompson** [gilesknap/gphotos-sync#220]
FINALLY!!!!
I found someone had an issue with a NFS mount and tried it:
`gphotos-sync  --db-path ./ /mnt/googlePhotos
`

I (partially) fixed the problem with:
`//andraia/GooglePhotos /mnt/googlePhotos cifs auto,username=username,password=password,vers=3.0,mfsymlinks,iocharset=utf8,file_mode=0777,dir_mode=0777,noperm 0 0
`
Now, when I run
```
gphotos-sync /mnt/googlePhotos/Jordan
04-15 21:45:33 WARNING  gphotos-sync 2.14.0 2020-04-15 21:45:33.238638
04-15 21:45:38 ERROR
Process failed.
Traceback (most recent call last):
  File "/home/jordan/.local/lib/python3.7/site-packages/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/home/jordan/.local/lib/python3.7/site-packages/gphotos/Main.py", line 263, in setup
    self.data_store = LocalData(db_path, args.flush_index)
  File "/home/jordan/.local/lib/python3.7/site-packages/gphotos/LocalData.py", line 54, in __init__
    self.clean_db()
  File "/home/jordan/.local/lib/python3.7/site-packages/gphotos/LocalData.py", line 106, in clean_db
    self.cur.executescript(qry)
sqlite3.OperationalError: database is locked
04-15 21:45:38 WARNING  Done.
```

This is old:

I installed with
`pip3 install gphotos-sync`

I tried to get this running on a local (USB) stick first.  I was able to get it running with:
`gphotos-sync  /mnt/usbdrive/test/
`
But I really wanted to get it working on My SMB drive is mounted like:
`//andraia/GooglePhotos /mnt/googlePhotos cifs auto,username=username,password=password,iocharset=utf8,file_mode=0777,dir_mode=0777,noperm 0 0
`
Here are the two drives:
```
ls -ltr /mnt
drwxrwxrwx 2 root root    0 Apr 14 23:33 googlePhotos
drwxr-xr-x 7 root root 4096 Apr 15 13:39 usbdrive
```
The only thing I can think of is that gphotos-sync thinks the SMB mount is a symbolic link.

This confuses me.  The first line says that symbolic links are not supported, the second says they are required:
```
04-15 10:19:31 ERROR    Symbolic links not supported
04-15 10:19:31 ERROR    Albums are not going to be synced - requires symlinks
```

This from previous attempts:

I think I have everything setup per the instructions.  
My target directory is an SMB share (/mnt/googlePhotos) so my command looks like this?:
`pipenv run ./gphotos-sync  /mnt/googlePhotos
`I get this error:
```
04-15 10:19:31 WARNING  gphotos-sync 2.14.0+4.37fad11.dirty 2020-04-15 10:19:30.510992
04-15 10:19:31 ERROR    Symbolic links not supported
04-15 10:19:31 ERROR    Albums are not going to be synced - requires symlinks
04-15 10:19:31 ERROR
Process failed.
Traceback (most recent call last):
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/Main.py", line 263, in setup
    self.data_store = LocalData(db_path, args.flush_index)
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/LocalData.py", line 55, in __init__
    self.check_schema_version()
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/LocalData.py", line 80, in check_schema_version
    self.cur.execute(query)
sqlite3.OperationalError: no such table: Globals
04-15 10:19:31 WARNING  Done.
```

It did create the log on the shared drive:
```
04-15 10:19:31 gphotos.Main WARNING  gphotos-sync 2.14.0+4.37fad11.dirty 2020-04-15 10:19:30.510992
04-15 10:19:31 gphotos.Utils DEBUG    MINIMUM_DATE = 1981-01-01 00:00:00
04-15 10:19:31 gphotos.Checks DEBUG    Checking if is filesystem supports symbolic links...
04-15 10:19:31 gphotos.Checks DEBUG    attempting to symlink /mnt/googlePhotos/test_src_1194621070 to /mnt/googlePhotos/test_dst_196706710
04-15 10:19:31 gphotos.Checks ERROR    Symbolic links not supported
04-15 10:19:31 gphotos.Checks ERROR    Albums are not going to be synced - requires symlinks
04-15 10:19:31 gphotos.Checks DEBUG    Checking if File system supports unicode filenames...
04-15 10:19:31 gphotos.Checks INFO     Filesystem supports Unicode filenames
04-15 10:19:31 gphotos.Checks DEBUG    Checking if File system is case insensitive...
04-15 10:19:31 gphotos.Checks INFO     Case insensitive file system found
04-15 10:19:31 gphotos.Checks INFO     Max Path Length: 4096
04-15 10:19:31 gphotos.Checks INFO     Max filename length: 255
04-15 10:19:31 gphotos.Main INFO     version: 2.14.0+4.37fad11.dirty, database schema version 5.7
04-15 10:19:31 gphotos.Main ERROR    
Process failed.
Traceback (most recent call last):
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/Main.py", line 263, in setup
    self.data_store = LocalData(db_path, args.flush_index)
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/LocalData.py", line 55, in __init__
    self.check_schema_version()
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/LocalData.py", line 80, in check_schema_version
    self.cur.execute(query)
sqlite3.OperationalError: no such table: Globals
04-15 10:19:31 gphotos.Main WARNING  Done.
04-15 10:19:31 gphotos.Main INFO     Elapsed time = 0:00:01.160188

```
It looks like the sqlite database was created, but there are no records in the tables.  I tried again with this command:
`python ./gphotos-sync --db-path /mnt/googlePhotos /mnt/googlePhotos
`
and I got this error:
```
04-15 12:53:02 WARNING  gphotos-sync 2.14.0+4.37fad11.dirty 2020-04-15 12:53:02.790750
04-15 12:53:03 ERROR    Symbolic links not supported
04-15 12:53:03 ERROR    Albums are not going to be synced - requires symlinks
/mnt/googlePhotos/gphotos.sqlite does not exist
04-15 12:53:03 ERROR
Process failed.
Traceback (most recent call last):
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/Main.py", line 263, in setup
    self.data_store = LocalData(db_path, args.flush_index)
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/LocalData.py", line 56, in __init__
    self.check_schema_version()
  File "/mnt/usbdrive/python/gphotos-sync/gphotos/LocalData.py", line 82, in check_schema_version
    version = float(self.cur.fetchone()[0])
TypeError: 'NoneType' object is not subscriptable
04-15 12:53:03 WARNING  Done.
```

**Comment by jorythompson** [comment]
There were two things that resolved this issue:
The way it was being called required the db-path option:
`gphotos-sync  --db-path ./ /mnt/googlePhotos
`
and 'mfsymlinks' was needed in the fstab:
`//andraia/GooglePhotos /mnt/googlePhotos cifs auto,username=username,password=password,vers=3.0,mfsymlinks,iocharset=utf8,file_mode=0777,dir_mode=0777,noperm 0 0
`

**Comment by gilesknap** [comment]
Thanks for the detailed report. I did not know about `mfsymlinks`

I already have a ticket to put the nfs mount issue in know problems - I'll add cifs to the list.
