### ISSUE TITLE
SQLite commit fails

### ISSUE THREAD

**Issue by skhaz** [gilesknap/gphotos-sync#224]
**Describe the bug**
Failed to commit after sync.

**To Reproduce**
Run gphotos-sync on a huge account, after 4 hours of syncing, the sqlite commit fails.:

```
04-21 19:08:44 INFO     Saving Database ...                                                                                                                                 
04-21 19:08:44 ERROR                                                                                                                                                        
Process failed.                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                          
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 418, in main                                                                                          
    self.start(args)                                                                                                                                                        
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 369, in start
    self.do_sync(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 366, in do_sync
    self.local_files_scan.find_missing_gphotos()
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalData.py", line 70, in __exit__
    self.store()
  File "/usr/local/lib/python3.7/site-packages/gphotos/LocalData.py", line 75, in store
    self.con.commit()
sqlite3.OperationalError: disk I/O error
04-21 19:08:44 WARNING  Done. 
04-21 19:08:44 INFO     Elapsed time = 4:50:29.598379 
```

**Comment by gilesknap** [comment]
Hi, what is the filesystem please? Has this happened more than once? What happens if you run the sync again without changing anything else?

**Comment by skhaz** [comment]
I use ZFS on FreeBSD. It always happen from now, used to work fine one month ago before I upgrade.

I'm running again without albums sync. Let's see how it works

**Comment by skhaz** [comment]
I ran again with `--skip-albums` and it worked

this is my script:
 
```
root@photos:/mnt/photos # cat /usr/local/bin/sync
#!/usr/bin/env bash

GPS=/usr/local/bin/gphotos-sync

HOME="${1?}"

declare -a ARGS=(
        --rescan
        --skip-albums
        --retry-download
        --max-threads 16 
        --photos-path .
        --albums-path .
        --secret /root/secret.json
        --log-level DEBUG 
)

(cd /mnt/photos || exit; LC_ALL=en_US.UTF-8 "$GPS" "${ARGS[@]}" "$HOME")
```

**Comment by skhaz** [comment]
I have one album of my son that's generated by google's AI tagging his face and this album is HUGE (proud father, you know 😅)

**Comment by gilesknap** [comment]
OK, well maybe the error should be taken on face value. I would keep an eye on that disk!

**Comment by skhaz** [comment]
Thanks @gilesknap
