### ISSUE TITLE
Error when running --compare 

### ISSUE THREAD

**Issue by arjunkc** [gilesknap/gphotos-sync#250]
**Describe the bug**
I simply run
```
gphotos-sync --compare old-google-photos-backup new-folder
```
It was giving errors on some gif and png files in the directory, and I moved these out. Even after doing so, it returns the following error
```
07-15 00:48:11 WARNING  gphotos-sync 2.14.2 2020-07-15 00:48:11.325817
07-15 00:48:11 WARNING  Indexing Google Photos Files ...
07-15 00:48:12 WARNING  indexed 0 items
07-15 00:48:12 WARNING  Downloading Photos ...
07-15 00:48:12 WARNING  Downloaded 0 Items, Failed 0, Already Downloaded 5657
07-15 00:48:12 WARNING  removing previous local scan data
07-15 00:48:12 WARNING  Indexing comparison folder /mnt/secondary_storage/Pictures/google_drive-arjunkc/Google Photos
07-15 00:48:37 WARNING  Indexed 1294 files in comparison folder /mnt/secondary_storage/Pictures/google_drive-arjunkc/Google Photos
07-15 00:48:37 WARNING  updating index with extra metadata for comparison (may take some time) ...
07-15 00:48:40 ERROR
Process failed.
Traceback (most recent call last):
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/plum/_plum.py", line 978, in unpack_from
    items, _offset = _unpack(fmt, buffer, offset, False, None)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/plum/_plum.py", line 790, in _unpack
    items, offset = fmt.__unpack__(buffer, offset, None, dump)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/plum/structure/_structure.py", line 93, in __unpack__
    item, offset = item_cls.__unpack__(buffer, offset, self, dump)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/plum/int/enum/_enum.py", line 60, in __unpack__
    value = cls(value)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 32759 is not a valid TiffByteOrder

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/plum/_plum.py", line 790, in _unpack
    items, offset = fmt.__unpack__(buffer, offset, None, dump)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/plum/structure/_structure.py", line 89, in __unpack__
    dump.add_record(access=f'[{i}] (.{name})', cls=item_cls))
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/plum/int/enum/_enum.py", line 60, in __unpack__
    value = cls(value)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 32759 is not a valid TiffByteOrder

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/gphotos/Main.py", line 418, in main
    self.start(args)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/gphotos/Main.py", line 369, in start
    self.do_sync(args)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/gphotos/Main.py", line 365, in do_sync
    self.google_photos_idx.get_extra_meta()
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/gphotos/GooglePhotosIndex.py", line 242, in get_extra_meta
    local_file = LocalFilesMedia(file_path)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/gphotos/LocalFilesMedia.py", line 89, in __init__
    self.get_exif()
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/gphotos/LocalFilesMedia.py", line 137, in get_exif
    self.__exif = exif.Image(image_file)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/exif/_image.py", line 75, in __init__
    self._parse_segments(img_bytes)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/exif/_image.py", line 55, in _parse_segments
    self._segments['APP1'] = App1MetaData(img_bytes[app1_start_index:cursor])
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/exif/_app1_metadata.py", line 373, in __init__
    self._parse_ifd_segments()
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/exif/_app1_metadata.py", line 315, in _parse_ifd_segments
    tiff_header = unpack_from(TiffHeader, self.body_bytes)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/plum/_plum.py", line 981, in unpack_from
    unpack_from_and_dump(fmt, buffer, offset)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/plum/_plum.py", line 1041, in unpack_from_and_dump
    items, _offset = _unpack(fmt, buffer, offset, False, dump)
  File "/usr/local/virtualenv/python3.6/lib/python3.6/site-packages/plum/_plum.py", line 852, in _unpack
    raise UnpackError(unexpected_exception)
plum._exceptions.UnpackError:

+--------+-------------------+-------+-------+---------------+
| Offset | Access            | Value | Bytes | Type          |
+--------+-------------------+-------+-------+---------------+
|        |                   |       |       | TiffHeader    |
| 0      | [0] (.byte_order) |       | f7 7f | TiffByteOrder |
+--------+-------------------+-------+-------+---------------+

ValueError occurred during unpack operation:

32759 is not a valid TiffByteOrder
07-15 00:48:40 WARNING  Done.
```

**To Reproduce**
It's kind of hard to reproduce the behavior without giving you an exact copy of my local repository.

**Comment by gilesknap** [comment]
It looks like there is a badly formatted exif in one of your files. The code does not handle this well so I'll have to add some better error handling in this area and get you to try again.

**Comment by arjunkc** [comment]
Thanks! I'm happy to try any bug fixes.

Quoting Giles Knap (2020-07-15 04:59:19)

**Comment by rkraats** [comment]
FYI, I ran into the same issue for a lot of my archived files. Downgrading the exif module (https://pypi.org/project/exif/) from 1.0.0 to an older version (0.10.0 picked randomly, `pipenv install exif==0.10.0`) 'fixed' the exception. According to https://gitlab.com/TNThieding/exif/-/blob/master/docs/release_notes.rst it may be the use of this 'plum' package since 0.11.2 that gives this issue.

**Comment by arjunkc** [comment]
I downgraded to version 0.10.0 and it worked for me. Downgrading to higher versions like 0.12.0 didn't work, however.

Quoting Roel van de Kraats (2020-07-21 13:44:04)

**Comment by gilesknap** [comment]
I've just seen this bug in #251. It looks like I need to pin the version of exif for the moment.

Thanks for the input @arjunkc @rkraats

**Comment by gilesknap** [comment]
this is now fixed in the exif library

**Comment by mkatsevVR** [comment]
fyi, I got the same error with the same stacktrace on exif 1.0.4

```
plum._exceptions.UnpackError:

+--------+-------------------+-------+-------+---------------+
| Offset | Access            | Value | Bytes | Type          |
+--------+-------------------+-------+-------+---------------+
|        |                   |       |       | TiffHeader    |
| 0      | [0] (.byte_order) |       | 06 01 | TiffByteOrder |
+--------+-------------------+-------+-------+---------------+

ValueError occurred during unpack operation:

262 is not a valid TiffByteOrder
```

also perhaps the entire program should not crash from a single corrupted file?

**Comment by gilesknap** [comment]
OK - I can add an exception catch and make this a warning.

**Comment by willleeney** [comment]
+1 same error. No comparison folder is generated as a result

**Comment by gilesknap** [comment]
I'm afraid I've deprecated this feature because its too hard to maintain. Sorry about that but there is not enough metadata in google photos to reliably match files.
