### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by tarasglek** [gilesknap/gphotos-sync#256]
**Describe the bug**
Was syncing my library for first time got this error.

**To Reproduce**
Process failed.
Traceback (most recent call last):
File "/home/taras/.local/share/virtualenvs/gphotos-sync-Grs4-dzk/lib/python3.8/site-packages/gphotos/Main.py", line 418, in main
self.start(args)
File "/home/taras/.local/share/virtualenvs/gphotos-sync-Grs4-dzk/lib/python3.8/site-packages/gphotos/Main.py", line 369, in start
self.do_sync(args)
File "/home/taras/.local/share/virtualenvs/gphotos-sync-Grs4-dzk/lib/python3.8/site-packages/gphotos/Main.py", line 358, in do_sync
self.google_albums_sync.create_album_content_links()
File "/home/taras/.local/share/virtualenvs/gphotos-sync-Grs4-dzk/lib/python3.8/site-packages/gphotos/GoogleAlbumsSync.py", line 297, in create_album_content_links
if not link_folder.is_dir():
File "/usr/lib/python3.8/pathlib.py", line 1398, in is_dir
return S_ISDIR(self.stat().st_mode)
File "/usr/lib/python3.8/pathlib.py", line 1189, in stat
return self._accessor.stat(self)
OSError: [Errno 36] File name too long: "/photos/XXXXXX@gmail.com/albums/2018/0214 Last day in Park City. Didn't beat the high score of 15300 vertical feet yesterday. Made it to 12600 since there was a leg bruising fall for Bobi on some difficult terrain. The cocoa is on her chest to help her costrocondritis (cartilage inflammation). She loved it as she watched Olympics on tv."

**Comment by tarasglek** [comment]
Looks like it's due to ZFS 256 char limit

**Comment by tarasglek** [comment]
Looks like `--max-filename 150` does not apply to that particular stat call :(

**Comment by gilesknap** [comment]
This looks like two bugs. I should correctly discover the filename length
for zfs and also honour max file length for all file system activity.

I'll take a look

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
