### ISSUE TITLE
Oauth2 updated procedure/token expired error

### ISSUE THREAD

**Issue by miketunes** [gilesknap/gphotos-sync#257]
I haven't ran this for awhile, when I tried it I get this error:
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

I'm looking at these instructions, and it looks like they changed my token from external to internal.  When I try to change it back to external it asks this, is this a new requirement?  
https://docs.google.com/document/d/1ck1679H8ifmZ_4eVbDeD_-jezIcZ-j6MlaNaeQiz7y0/edit?usp=sharing

"Your app will be available to any user with a Google Account.
You've configured your app in a way that requires verification. To complete verification, you will need to provide:
An official link to your app's Privacy Policy
A YouTube video showing how you plan to use the Google user data you get from scopes
A written explanation telling Google why you need access to sensitive and/or restricted user data
All your domains verified in Google Search Console"

**Comment by gilesknap** [comment]
This does not sound good! I'll run through token generation and verify that
there is an issue - from your description Google may have changed policy
and be attempting to shut down projects like this. Hopefully it's just that
the procedure needs updating.

**Comment by gilesknap** [comment]
OK I have run through the procedure and it still works as before for me. I do get a message that says that the token has been set to external and I leave it as that. Then I get to select the application type as desktop.

**Comment by miketunes** [comment]
I went ahead and deleted the existing token and created a new one, it didn't prompt me to verify it this time.  I replaced the old token with the new one, named it client_secret.json under C:\Users\<username>\AppData\Local\gphotos-sync\gphotos-sync\

Running the command it still says token expired though, any ideas?  Here's the full output:
C:\gphotos>C:\Users\mike\AppData\Local\Programs\Python\Python36\python.exe -m pipenv run gphotos-sync --flush-index --do-delete --skip-albums C:\Google_Photos
09-07 16:31:11 WARNING  gphotos-sync 2.14.2 2020-09-07 16:31:11.168853
09-07 16:31:11 ERROR
Process failed.
Traceback (most recent call last):
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\requests_oauthlib\oauth2_session.py", line 478, in request
    url, http_method=method, body=data, headers=headers
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\gphotos\Main.py", line 417, in main
    self.setup(args, db_path)
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\gphotos\Main.py", line 309, in setup
    self.google_photos_client = RestClient(photos_api_url, self.auth.session)
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\gphotos\restclient.py", line 38, in __init__
    service_document = self.auth_session.get(api_url).json()
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\requests_oauthlib\oauth2_session.py", line 497, in request
    self.auto_refresh_url, auth=auth, **kwargs
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\requests_oauthlib\oauth2_session.py", line 446, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "c:\users\mike\.virtualenvs\gphotos-8kqg621w\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Bad Request
09-07 16:31:11 WARNING  Done.

**Comment by gilesknap** [comment]
Hi, I think we may have a confusion between user token and client secret here. (I should have picked this up before sorry!)

The client secret need only be set up once and should work forever - this is what the document 
https://docs.google.com/document/d/1ck1679H8ifmZ_4eVbDeD_-jezIcZ-j6MlaNaeQiz7y0/edit?usp=sharing is all about.

Then you get a user token when you log in using your user credentials. Once you have done this we usually don't need to ask for credentials again since I request a refresh token whenever this expires. Something has gone wrong with your refresh and you need to enter your user credentials again. 

To do this run gphotos-sync with --new-token argument.

You have now also updated your client secret but this should not matter although it was unnecessary.

**Comment by gilesknap** [comment]
I believe this is resolved. closing.

**Comment by Alives** [comment]
FWIW the token is stored in a file wherever your /storage is called `.gphotos.token`.
