### ISSUE TITLE
sqlite3.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by skhaz** [gilesknap/gphotos-sync#275]
**Describe the bug**
I am using `gcsfuse` to mount a google cloud storage FUSE directory and when I run the gphotos-sync I got this error

```
gphotos-sync .
12-27 01:36:48 WARNING  gphotos-sync 2.14.2 2020-12-27 01:36:47.964893 
12-27 01:36:53 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gphotos/Main.py", line 263, in setup
    self.data_store = LocalData(db_path, args.flush_index)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gphotos/LocalData.py", line 53, in __init__
    self.clean_db()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gphotos/LocalData.py", line 105, in clean_db
    self.cur.executescript(qry)
sqlite3.OperationalError: disk I/O error
12-27 01:36:53 WARNING  Done
```

**To Reproduce**
Mount a google cloud storage bucket using gcsfuse then run gphotos-sync .

**Comment by gilesknap** [comment]
This will be because the sqlite dB cannot exist in at drive suite to locking issues.

We have a workaround which is to keep the dB file only in a local drive. Please see the --db-path argument.

**Comment by skhaz** [comment]
Thanks @gilesknap. I didn't notice the `--db-path`! This solve my problem
