### ISSUE TITLE
Authorization Issue

### ISSUE THREAD

**Issue by moussaba** [gilesknap/gphotos-sync#282]
**Describe the bug**
After entering the response token the process stops with the error below
01-15 05:17:37 WARNING  gphotos-sync 2.14.2 2021-01-15 05:17:37.831596 
01-15 05:17:38 WARNING  Indexing Google Photos Files ... 
01-15 05:17:38 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 418, in main
    self.start(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 369, in start
    self.do_sync(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 333, in do_sync
    self.google_photos_idx.index_photos_media()
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosIndex.py", line 154, in index_photos_media
    favourites=self.favourites,
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosIndex.py", line 119, in search_media
    pageToken=page_token, pageSize=self.PAGE_SIZE
  File "/usr/local/lib/python3.7/site-packages/gphotos/restclient.py", line 100, in execute
    result.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://photoslibrary.googleapis.com/v1/mediaItems?pageSize=100
01-15 05:17:38 WARNING  Done. 

**To Reproduce**
Steps to reproduce the behaviour:

**Comment by gilesknap** [comment]
I think the likely cause of this is that although you created a secret correctly you did not add all the photos permissions to it. Please can you retry generation of the secret and pay close attention to the section 'Enable Google Photos API'

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
