### ISSUE TITLE
Long filenames

### ISSUE THREAD

**Issue by lutzky** [gilesknap/gphotos-sync#285]
It turns out that some of my old photos in Google Photos have quite long, Unicode (originally Hebrew) filenames. As far as I can tell, there is unfortunately no way to change the underlying filename in Google Photos. This leads to this kind of problem:

```
Traceback (most recent call last):
  File "/home/ohad/.local/share/virtualenvs/photos-aX3072vj/lib/python3.8/site-packages/gphotos/Main.py", line 418, in main                                                                                                                       self.start(args)
  File "/home/ohad/.local/share/virtualenvs/photos-aX3072vj/lib/python3.8/site-packages/gphotos/Main.py", line 369, in start                                                                                                                      self.do_sync(args)
  File "/home/ohad/.local/share/virtualenvs/photos-aX3072vj/lib/python3.8/site-packages/gphotos/Main.py", line 358, in do_sync                                                                                                                    self.google_albums_sync.create_album_content_links()
  File "/home/ohad/.local/share/virtualenvs/photos-aX3072vj/lib/python3.8/site-packages/gphotos/GoogleAlbumsSync.py", line 306, in create_album_content_links                                                                                    link_file.symlink_to(relative_filename)
  File "/usr/lib/python3.8/pathlib.py", line 1379, in symlink_to                                                            self._accessor.symlink(target, self, target_is_directory)
  File "/usr/lib/python3.8/pathlib.py", line 442, in symlink                                                                return os.symlink(a, b)
OSError: [Errno 36] File name too long: '../../../photos/2010/09/______________ __________ ________________________________ - __________ ______ ________ ____________ ______________ __________ ________________________________ ______ ____ ________. ____ __________ ________ ________, ____ __________ ______________ :)' -> '/media/photos/backup/albums/2010/1002 Greece 2010/0103_______________ __________ ________________________________ - __________ ______ ________ ____________ ______________ __________ ________________________________ ______ ____ ________. ____ __________ ________ ________, ____ __________ ______________ :)'
```

Would it perhaps make sense to have a flag to use some underling UUID instead of the original filename for people with this issue?

**Comment by lutzky** [comment]
Ahh, I see that `gphotos-sync` is already trying to deal with this via `max_path`. Things that might be confusing it further:

* Weird filename encoding (it's actually not unicode, it seems)
* ZFS

I'll investigate further.

**Comment by lutzky** [comment]
Ah, OK, it's simpler: The filename is 253 characters long, but the proposed symlink would have a leading `1234_`, pushing it over the limit.

**Comment by gilesknap** [comment]
Thanks, that is an easy to fix bug probably. I'll take look soon. Or you
can do a PR if you fancy.

**Comment by lutzky** [comment]
Yep, PR took two a couple of attempts. It also seems to have uncovered another issue, #288.
