### ISSUE TITLE
error in authorization

### ISSUE THREAD

**Issue by haayman** [gilesknap/gphotos-sync#289]
I'm trying to add a token, but the script errs on authorize.py and doesn't wait for my input

This is the log:
~/gphotos-sync$ pipenv run gphotos-sync $PWD
01-24 14:41:54 WARNING  gphotos-sync 2.14.2 2021-01-24 14:41:54.638257 
Please go here and authorize, https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=[removed_client_id]&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.sharing&state=[removed_state]&access_type=offline&prompt=select_account
Paste the response token here:01-24 14:41:54 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/home/caroline/.local/share/virtualenvs/caroline-y_oGhXt6/lib/python3.6/site-packages/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/home/caroline/.local/share/virtualenvs/caroline-y_oGhXt6/lib/python3.6/site-packages/gphotos/Main.py", line 284, in setup
    self.auth.authorize()
  File "/home/caroline/.local/share/virtualenvs/caroline-y_oGhXt6/lib/python3.6/site-packages/gphotos/authorize.py", line 103, in authorize
    response_code = input("Paste the response token here:")
EOFError
01-24 14:41:54 WARNING  Done. 

**To Reproduce**
Steps to reproduce the behaviour:
I have no idea

**Comment by haayman** [comment]
I'm sorry. Can disregard. After logging in again it worked. No clue what happened
