### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by brianrook** [gilesknap/gphotos-sync#300]
**Describe the bug**
Getting this error in my logs:

```
02-23 00:13:40 WARNING  Indexing Google Photos Files ...
02-23 00:13:49 WARNING  indexed 1769 items
02-23 00:13:49 WARNING  Downloading Photos ...
02-23 00:13:51 ERROR    FAILURE 1 downloading photos/2021/02/PXL_20210220_180852140.jpg - ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
02-23 00:13:51 ERROR    FAILURE 2 downloading photos/2021/02/PXL_20210220_180914340.jpg - ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
02-23 00:13:52 ERROR
Process failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 437, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 151, in download_photo_media
    self.download_batch(batch)
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 192, in download_batch
    self.download_file(media_item, media_item_json)
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 223, in download_file
    self.do_download_complete(done_list)
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 327, in do_download_complete
    raise e
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 257, in do_download_file
    shutil.copyfileobj(response.raw, temp_file)
  File "/usr/local/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 418, in main
    self.start(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 369, in start
    self.do_sync(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 337, in do_sync
    files_downloaded = self.google_photos_down.download_photo_media()
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 155, in download_photo_media
    self.do_download_complete(futures_left)
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 327, in do_download_complete
    raise e
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 257, in do_download_file
    shutil.copyfileobj(response.raw, temp_file)
  File "/usr/local/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
02-23 00:13:52 WARNING  Done.

```

**To Reproduce**
This was working, but some permissions issue (my end) messed up my albums.  I tried to --rescan but that didn't work (similar error).  I blew away my backup, container and attempted to reinstall but I get the same error still.

**Comment by gilesknap** [comment]
Hi, I've not seen an error like this before but it sounds like the google servers do not like you. I think you should try --new-token and if that does not help then regenerate your secret. I'm not sure what else to try.

**Comment by gilesknap** [comment]
closing, please reopen if you want to discuss further.

**Comment by brianrook** [comment]
I've got someone on my blog that has the same issue.  I'm not sure what the root cause is.  It _appears_ that I can call google though (because I can get the auth and count endpoints).  I've seen some docs online that say it might be caused by applications that make requests too quickly and the python library can't track the threads (???).

Here's one that says it might be a library that needs to be updated:
https://stackoverflow.com/questions/41832838/python-error-104-connection-reset-by-peer

Here's one that said to introduce a delay (via sleep)
https://stackoverflow.com/questions/383738/104-connection-reset-by-peer-socket-error-or-when-does-closing-a-socket-resu

**Comment by gilesknap** [comment]
@brianrook if it simply too many requests then you can slow down gphotos-sync by dropping the no. of threads with --threads option. If you are still regularly seeing the error then please try that.

**Comment by brianrook** [comment]
I tried modifying the threads.  That didn't work.  I tried a different library from another developer and that didn't work either.  

So, I'm not sure why google doesn't like me... they don't have very good support.

I'm going to go ahead and just sync pictures directly from my phone to my NAS going forward and then use google takeout to get a one time extract.
