### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by giorgiooriani** [gilesknap/gphotos-sync#312]
Getting this issue, running in Docker on Synology NAS

04-30 17:51:18 ERROR
Process failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff7c566d810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7c566d810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 284, in setup
    self.auth.authorize()
  File "/usr/local/lib/python3.7/site-packages/gphotos/authorize.py", line 107, in authorize
    self.token_uri, client_secret=self.client_secret, code=response_code
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 344, in fetch_token
    **request_kwargs
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 516, in request
    method, url, headers=headers, data=data, **kwargs
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7c566d810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
04-30 17:51:18 WARNING  Done.

**Comment by joncamfield** [comment]
On a fresh install / first run I am getting this also. Happy to help/test/debug.  DS916+ running the docker latest tag (" gphotos-sync 2.14.2 " ; DSM version 6.2.4-25556

**Comment by gilesknap** [comment]
This is a little hard to diagnose without a Synology to try it on. It may be that the container has been launched without network access. Can you point to the instructions you used to install the image please?

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.

**Comment by bxm156** [comment]
For those who encounter this on a Synology, the likely cause is your Docker container is being blocked by your Firewall settings. You need to configure your Synology firewall to allow the Docker bridge IPs to access the internet.

I found this particularly helpful for setting up the configuration: https://www.reddit.com/r/synology/comments/vaqzbr/docker_bridge_issue/

**Comment by gilesknap** [comment]
thanks @bxm156
