### ISSUE TITLE
Can't make gphotos-sync working

### ISSUE THREAD

**Issue by beckietech** [gilesknap/gphotos-sync#333]
**Describe the bug**
Please kindly help since I am newbee to this library and I followed the link: https://www.linuxuprising.com/2019/06/how-to-backup-google-photos-to-your.html
and I got the following message:
pipenv run gphotos-sync ~/test
12-28 17:29:34 WARNING  gphotos-sync 2.14.2 2021-12-28 17:29:34.240905 
12-28 17:29:34 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/Users/beckie/.local/share/virtualenvs/gphotos-sync-8y_yJ_-E/lib/python3.9/site-packages/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/Users/beckie/.local/share/virtualenvs/gphotos-sync-8y_yJ_-E/lib/python3.9/site-packages/gphotos/Main.py", line 281, in setup
    self.auth = Authorize(
  File "/Users/beckie/.local/share/virtualenvs/gphotos-sync-8y_yJ_-E/lib/python3.9/site-packages/gphotos/authorize.py", line 46, in __init__
    secrets = all_json["installed"]
KeyError: 'installed'
12-28 17:29:34 WARNING  Done. 

Can someone please give me a hint of what happened?

**To Reproduce**
Steps to reproduce the behaviour:

**Comment by beckietech** [comment]
after retried, i finally got it working.. case closed
