### ISSUE TITLE
cannot import name 'external_account_authorized_user' from 'google.auth

### ISSUE THREAD

**Issue by gustavohenac** [gilesknap/gphotos-sync#397]
I run gphotos-sync (dir) as usual and works fine. After my last upgrade on arch linux, results in this message and doesn't work. I already reinstall but appears this message below: 

Traceback (most recent call last):
 File "/usr/bin/gphotos-sync", line 5, in <module>
    from gphotos_sync.Main import main
  File "/usr/lib/python3.10/site-packages/gphotos_sync/Main.py", line 14, in <module>
    from gphotos_sync.authorize import Authorize
  File "/usr/lib/python3.10/site-packages/gphotos_sync/authorize.py", line 6, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
  File "/usr/lib/python3.10/site-packages/google_auth_oauthlib/__init__.py", line 21,
in <module>
    from .interactive import get_user_credentials
  File "/usr/lib/python3.10/site-packages/google_auth_oauthlib/interactive.py", line 27, in <module>
    import google_auth_oauthlib.flow
  File "/usr/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 69, in <module>
    import google_auth_oauthlib.helpers
  File "/usr/lib/python3.10/site-packages/google_auth_oauthlib/helpers.py", line 27, in <module>
    from google.auth import external_account_authorized_user
ImportError: cannot import name 'external_account_authorized_user' from 'google.auth'
(/usr/lib/python3.10/site-packages/google/auth/__init__.py)

**Comment by gilesknap** [comment]
The authorization flow has changed and you will need to re-create your secret and token.
See 
https://gilesknap.github.io/gphotos-sync/main/tutorials/oauth2.html

**Comment by gilesknap** [comment]
I'm not convinced that this is the cause of your error though. It looks more like a dependency has not updated.
Can you create a new virtual env and reinstall?

**Comment by gustavohenac** [comment]
> The authorization flow has changed and you will need to re-create your secret and token. See https://gilesknap.github.io/gphotos-sync/main/tutorials/oauth2.html

Authorized domains in mandatory now. I don't have any page yet so until now i can't pass this step.

**Comment by gustavohenac** [comment]
> I'm not convinced that this is the cause of your error though. It looks more like a dependency has not updated. Can you create a new virtual env and reinstall?

actually i using by paru (helper) without env. in the past, always worked well. i didn't can solve until now.

**Comment by gilesknap** [comment]
Sorry I can't help you with any Arch specific things!

But what you need to do is remove the python dependencies previously installed and then re-install gphotos-sync.

This is my bad because I have not used specific enough dependencies in the project - need to fix this.

**Comment by gustavohenac** [comment]
That's ok. I already removed them with helper and reinstall. I will wait for next fixed version. Thanks. I really like your software. Regards from Brazil.

**Comment by wdirksen** [comment]
There is another new dependency issue with recent update of python-plum (0.7.9-1 -> 0.8.5-1) in ArchLinux

Reporting errors with updated dependencies is meant to be of some value. Let me know if should stop doing this

**Comment by gilesknap** [comment]
thanks @wdirksen. If you a set of dependency pins that works for you, please could you share it?

i should have a bit of time this week to do a release to resolve a few issues including lack of dependency pinning.
