### ISSUE TITLE
InvalidCredentialsError('Credentials file cannot be symbolic link')

### ISSUE THREAD

**Issue by arkpoah** [gilesknap/gphotos-sync#4]
Hi,
using in virtualenv and run script like this : python gphotos-sync /syncdir/
I get auth url and enter code, it success then I get error : 
Authentication successful.
Traceback (most recent call last):
  File "gphotos-sync", line 7, in <module>
    g.main()
  File "/home/ark/gphotos-sync/Main.py", line 168, in main
    self.setup(args)
  File "/home/ark/gphotos-sync/Main.py", line 120, in setup
    credentials_json=credentials_file)
  File "/home/ark/gphotos-sync/GoogleDriveSync.py", line 59, in __init__
    self._g_auth.CommandLineAuth()
  File "/home/ark/gphotos-sync/venv/local/lib/python2.7/site-packages/pydrive/auth.py", line 127, in _decorated
    self.SaveCredentials()
  File "/home/ark/gphotos-sync/venv/local/lib/python2.7/site-packages/pydrive/auth.py", line 327, in SaveCredentials
    self.SaveCredentialsFile()
  File "/home/ark/gphotos-sync/venv/local/lib/python2.7/site-packages/pydrive/auth.py", line 349, in SaveCredentialsFile
    raise InvalidCredentialsError('Credentials file cannot be symbolic link')
pydrive.auth.InvalidCredentialsError: Credentials file cannot be symbolic link

thx

**Comment by gilesknap** [comment]
Hi, this is an issue with the pydrive as far as understand it. It requires the directory for the credentials file to exist the first time you create it. I believe it is '.local/share/gphotos-sync' .

Thanks for the reminder, I'll put a workaround in the code to create this before calling auth.

**Comment by gilesknap** [comment]
Also, if you are trying this code, I recommend you look at the rc1 branch that I just committed, it is much improved and will be going into master for a release in the next couple of days.

**Comment by arkpoah** [comment]
Thanks, it works with ~/.local/share/gphotos-sync folder.

unfortunately I get another error after database saved :
- in master branch

Saving Database ...
Database Saved.

Traceback (most recent call last):
  File "gphotos-sync", line 7, in <module>
    g.main()
  File "/home/ark/gphotos-sync/Main.py", line 169, in main
    self.start(args)
  File "/home/ark/gphotos-sync/Main.py", line 141, in start
    self.drive_sync.index_drive_media()
  File "/home/ark/gphotos-sync/GoogleDriveSync.py", line 160, in index_drive_media
    self._root_folder, drive_file)
  File "/home/ark/gphotos-sync/GoogleDriveMedia.py", line 19, in __init__
    if self.parent_id in folder_paths:
  File "/home/ark/gphotos-sync/GoogleDriveMedia.py", line 100, in parent_id
    return self.__drive_file["parents"][self.__parent_num]["id"]
IndexError: list index out of range


- in rc1 branch

Traceback (most recent call last):
  File "gphotos-sync", line 7, in <module>
    g.main()
  File "/home/ark/gphotos-sync/Main.py", line 153, in main
    self.setup(args)
  File "/home/ark/gphotos-sync/Main.py", line 93, in setup
    self.data_store = LocalData(args.root_folder, args.flush_index)
  File "/home/ark/gphotos-sync/LocalData.py", line 99, in __init__
    self.check_schema_version()
  File "/home/ark/gphotos-sync/LocalData.py", line 134, in check_schema_version
    self.cur.execute(query)
sqlite3.OperationalError: no such column: Id

**Comment by gilesknap** [comment]
Ok with the rc1 please try --flush-index option.

**Comment by arkpoah** [comment]
I get same error than in master branch with --flush-index

**Comment by gilesknap** [comment]
I think this may mean that you have not connected Google photos to drive.
If you do not see a folder "Google Photos" in the root of your Google drive
in the Google drive web app then this is the case.

You could add Google photos to drive (see Google info on how to) or you
could use the --skip-drive option in which case all of your photos would
download via the Picasa API.

Let me know if this works. Thanks.

**Comment by arkpoah** [comment]
Ok you're right, google photos is not connected to drive, sorry.
It works fine with --skip-drive.
Thanks !

**Comment by gilesknap** [comment]
Thanks for the testing, I'll put a check in with a relevant message.
