### ISSUE TITLE
first run on fstab mounted NTFS filesystem produces error

### ISSUE THREAD

**Issue by samandiriel** [gilesknap/gphotos-sync#497]
Running it locally (not virtually) on Ubuntu 22.04.4 LTS with fstab mounting a network share on a windows machine on the network, trying to run for first time produces this output:

```
$ gphotos-sync /mount/raid1_14tb/docs/Photos/gphotos-sync --case-insensitive-fs --max-threads 10 --ntfs
07-12 08:50:09 WARNING  gphotos-sync 3.2.4 2024-07-12 08:50:09.816744 
07-12 08:50:09 ERROR    Symbolic links not supported 
07-12 08:50:09 ERROR    Albums are not going to be synced - requires symlinks 
07-12 08:50:10 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/home/logos/.local/lib/python3.10/site-packages/gphotos_sync/__main__.py", line 552, in main
    self.setup(args, db_path)
  File "/home/logos/.local/lib/python3.10/site-packages/gphotos_sync/__main__.py", line 347, in setup
    self.data_store = LocalData(db_path, args.flush_index)
  File "/home/logos/.local/lib/python3.10/site-packages/gphotos_sync/LocalData.py", line 59, in __init__
    self.check_schema_version()
  File "/home/logos/.local/lib/python3.10/site-packages/gphotos_sync/LocalData.py", line 84, in check_schema_version
    self.cur.execute(query)
sqlite3.OperationalError: no such table: Globals
07-12 08:50:10 WARNING  Done. 
```

Works fine when I run it on a local folder tho...

**Comment by samandiriel** [comment]
If I copy over the files from the local instance to the mounted instance, things go a little further but are still fubar'd:

```
$ gphotos-sync /mount/raid1_14tb/docs/Photos/gphotos-sync --case-insensitive-fs --max-threads 10 --ntfs
07-12 09:04:30 WARNING  gphotos-sync 3.2.4 2024-07-12 09:04:30.831318 
07-12 09:04:30 ERROR    Symbolic links not supported 
07-12 09:04:30 ERROR    Albums are not going to be synced - requires symlinks 
07-12 09:04:31 WARNING  Indexing Google Photos Files ... 
07-12 09:04:31 WARNING  indexed 0 items 
07-12 09:04:31 WARNING  Downloading Photos ... 
07-12 09:04:31 WARNING  Downloaded 0 Items, Failed 0, Already Downloaded 107 
07-12 09:04:37 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/home/logos/.local/lib/python3.10/site-packages/gphotos_sync/__main__.py", line 553, in main
    self.start(args)
  File "/home/logos/.local/lib/python3.10/site-packages/gphotos_sync/__main__.py", line 471, in start
    self.do_sync(args)
  File "/home/logos/.local/lib/python3.10/site-packages/gphotos_sync/__main__.py", line 432, in do_sync
    with self.data_store:
  File "/home/logos/.local/lib/python3.10/site-packages/gphotos_sync/LocalData.py", line 74, in __exit__
    self.store()
  File "/home/logos/.local/lib/python3.10/site-packages/gphotos_sync/LocalData.py", line 79, in store
    self.con.commit()
sqlite3.OperationalError: database is locked
07-12 09:04:37 WARNING  Done. 
```

**Comment by samandiriel** [comment]
Permissions are rxw on both the ubuntu and windows views of the gphotos.sqlite file

**Comment by gilesknap** [comment]
Hi @samandiriel.

Sqlite does not like some filesystems, it is due to the lock semantics - I have forgotten the details but they are discussed in a closed issue somewhere.

We have a workaround which is to keep the dB file only in a local drive. Please see the --db-path argument to choose where your database files go and keep that on a local file system.
