### ISSUE TITLE
libmagic dependency not well documented

### ISSUE THREAD

**Issue by wilhuff** [gilesknap/gphotos-sync#67]
I'm running gphotos-sync from source (at e28ab678661fe96aff2b0236d76b8e0331650f57) via pipenv on macOS 10.14.3.

On my first run of `pipenv run gphotos-sync`, I encountered the following error (with my home directory replaced with `...`):

```
Traceback (most recent call last):
  File ".../.local/share/virtualenvs/gphotos-sync-Al_Gqc-6/bin/gphotos-sync", line 6, in <module>
    from gphotos.Main import main
  File ".../.local/share/virtualenvs/gphotos-sync-Al_Gqc-6/lib/python3.6/site-packages/gphotos/Main.py", line 11, in <module>
    from gphotos.GooglePhotosIndex import GooglePhotosIndex
  File ".../.local/share/virtualenvs/gphotos-sync-Al_Gqc-6/lib/python3.6/site-packages/gphotos/GooglePhotosIndex.py", line 9, in <module>
    from gphotos.LocalFilesMedia import LocalFilesMedia
  File ".../.local/share/virtualenvs/gphotos-sync-Al_Gqc-6/lib/python3.6/site-packages/gphotos/LocalFilesMedia.py", line 12, in <module>
    import magic
  File ".../.local/share/virtualenvs/gphotos-sync-Al_Gqc-6/lib/python3.6/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

I managed to work around this with:

```bash
$ brew install libmagic
$ DYLD_LIBRARY_PATH=$(brew --prefix)/opt/libmagic/lib pipenv run gphotos-sync
```

It may be worth adding instructions to your getting started docs about this or linking to official ones (though I couldn't find such a thing).

**Comment by gilesknap** [comment]
Thanks for the info. I noticed a similar issue installing on Windows. I
guess you are on Mac?

My solution on the development branch is to upgrade to python 3.7 and use
built in support for mime types.

Would that work for you?

**Comment by wilhuff** [comment]
I'm in a working state, so I filed this as an FYI. Yes I'm on a Mac, running macOS 10.14.3 (Mojave) which was the latest version as of this writing.

Using python's built-in support sounds like a great idea.

**Comment by gilesknap** [comment]
OK, I'll release the version based on Python 3.7

**Comment by gilesknap** [comment]
There is now a 3.8.5 release which requires python 3.7 and not magic.
