### ISSUE TITLE
Albums: sqlite3.IntegrityError: UNIQUE constraint failed

### ISSUE THREAD

**Issue by stloewen** [gilesknap/gphotos-sync#71]
Using the latest gphotos-sync from pip I get the following error:

```
05-02 10:36:03 gphotos.Main INFO     version: 2.8.4, database schema version 5.5

... [lots of stuff]

05-02 10:36:45 gphotos.GoogleAlbumsSync DEBUG    ----IMG_9221.JPG
05-02 10:36:45 gphotos.GoogleAlbumsSync DEBUG    Adding album media item IMG_9221.JPG IMG_9221.JPG 0
05-02 10:36:45 gphotos.LocalData ERROR    SQL constraint issue with {'Id': None, 'RemoteId': 'ACRh3gqCCT_vymB8jbmorjC2maJnst6hZ38SAVHFT6LfyVFuR0gM5PDCux8WmyVT9OTiNlY2kYUJ', 'Uid': None, 'Url': 'https://photos.google.com/lr/album/ACRh3gq_zchp4OuyC-ckn7q1LQ-wi1HDEFs09X07qxt1zykWePfxUPSghrf4zcD-fHjM8UV6YDhu/photo/ACRh3gqCCT_vymB8jbmorjC2maJnst6hZ38SAVHFT6LfyVFuR0gM5PDCux8WmyVT9OTiNlY2kYUJ', 'Path': '/mnt/ironwolf/data/backups/google-photos/stefans-fotos/photos/2016/08', 'FileName': 'IMG_9221.JPG', 'OrigFileName': 'IMG_9221.JPG', 'DuplicateNo': 0, 'FileSize': 0, 'MimeType': 'image/jpeg', 'Description': '', 'ModifyDate': datetime.datetime(1970, 1, 1, 0, 0), 'CreateDate': datetime.datetime(2016, 8, 17, 16, 13, 6), 'SyncDate': '2019-05-02 10:36:45', 'Downloaded': 0, 'empty': False}
05-02 10:36:45 gphotos.LocalData INFO     Saving Database ...
05-02 10:36:45 gphotos.LocalData INFO     Database Saved.
05-02 10:36:45 gphotos.Main ERROR    
Process failed.
Traceback (most recent call last):
  File "/home/stefan/.local/share/virtualenvs/google-photos-xV_lfNiP/lib/python3.6/site-packages/gphotos/Main.py", line 261, in main
    self.start(args)
  File "/home/stefan/.local/share/virtualenvs/google-photos-xV_lfNiP/lib/python3.6/site-packages/gphotos/Main.py", line 215, in start
    self.google_albums_sync.index_album_media()
  File "/home/stefan/.local/share/virtualenvs/google-photos-xV_lfNiP/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 88, in index_album_media
    False, True)
  File "/home/stefan/.local/share/virtualenvs/google-photos-xV_lfNiP/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 126, in index_albums_type
    album.id, add_media_items)
  File "/home/stefan/.local/share/virtualenvs/google-photos-xV_lfNiP/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 75, in fetch_album_contents
    GooglePhotosRow.from_media(media_item), False)
  File "/home/stefan/.local/share/virtualenvs/google-photos-xV_lfNiP/lib/python3.6/site-packages/gphotos/LocalData.py", line 139, in put_row
    self.cur.execute(query, row.dict)
sqlite3.IntegrityError: UNIQUE constraint failed: SyncFiles.Path, SyncFiles.FileName, SyncFiles.DuplicateNo
05-02 10:36:45 gphotos.Main WARNING  Done.
05-02 10:36:45 gphotos.Main INFO     Elapsed time = 0:00:41.641234
```

As the backtrace suggests, running with `--skip-albums` does not yield the error.

Happens on an existing database as well as an empty one.

**Comment by stloewen** [comment]
This is already fixed on master. Sorry.

**Comment by gilesknap** [comment]
Don't apologize, you have given me a heads up that I need to make another
release to pypi. Thanks for letting me know. I'll do the release over the
weekend.
