### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:

### ISSUE THREAD

**Issue by kholmatov** [gilesknap/gphotos-sync#88]
`gphotos-sync videofolder
07-21 11:33:58 Indexing Google Photos Files ...
07-21 11:33:58 
Process failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gphotos_sync-2.9.1-py3.6.egg/gphotos/Main.py", line 339, in main
    self.start(args)
  File "/usr/local/lib/python3.6/dist-packages/gphotos_sync-2.9.1-py3.6.egg/gphotos/Main.py", line 311, in start
    self.do_sync(args)
  File "/usr/local/lib/python3.6/dist-packages/gphotos_sync-2.9.1-py3.6.egg/gphotos/Main.py", line 286, in do_sync
    new_files = self.google_photos_idx.index_photos_media()
  File "/usr/local/lib/python3.6/dist-packages/gphotos_sync-2.9.1-py3.6.egg/gphotos/GooglePhotosIndex.py", line 146, in index_photos_media
    favourites=self.favourites)
  File "/usr/local/lib/python3.6/dist-packages/gphotos_sync-2.9.1-py3.6.egg/gphotos/GooglePhotosIndex.py", line 110, in search_media
    pageToken=page_token, pageSize=self.PAGE_SIZE).json()
  File "/usr/local/lib/python3.6/dist-packages/gphotos_sync-2.9.1-py3.6.egg/gphotos/restclient.py", line 86, in execute
    result.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://photoslibrary.googleapis.com/v1/mediaItems?pageSize=100
07-21 11:33:58 Done.`

**Comment by kholmatov** [comment]
Must **Enabled** "_Photos Library API_" in Google Developer Console

**Comment by gilesknap** [comment]
Thanks for answering your question. I'm going to create a troubleshooting page and I'll put this issue on it.
